name: Create PR - Promote to `prod` from `main`

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Promote 'main' to 'prod'
        id: promote
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git checkout main
          git fetch origin main
          git pull
          gh pr create --base prod --head main --title "AUTO PR: Promote 'main' to 'prod'" --label auto-promote --fill > stdout.txt 2> stderr.txt || true
          if [ -s pr-url.txt ]; then
            echo "PR created:"
            cat stdout.txt
            exit 0
          fi
          if [ -s stderr.txt ]; then
            lastmsg=$(cat stderr.txt | tail -n 1)
            if [[ $lastmsg == *"https://github.com/"* ]]; then
              echo "PR already exists: $lastmsg"
              exit 0
            fi
            echo "There was an error when creating PR:"
            cat stderr.txt
            exit 1
          fi
          exit 1
