name: Create PR - Promote to `prod` from `main`

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Promote 'main' to 'prod'
        id: promote
        run: |
          gh pr create --base prod --head main --title "Auto promote 'main' to 'prod'" --fill > pr-url.txt 2> stderr.txt
          if [ -s stderr.txt ]; then
            cat stderr.txt
            exit 0
          fi
          if [ -s pr-url.txt ]; then
            echo "PR created:"
            cat pr-url.txt
            exit 0
          fi
          exit 1
